package dev.c0redev.volter;

import java.io.IOException;
import java.io.InputStream;
import java.security.SecureRandom;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.Properties;

final class Config {
  private final List<Integer> listenPorts;
  private final String token;
  private final int udpChannels;
  private final String publicHost;
  private final boolean debug;
  private final boolean updateEnabled;
  private final String updateRepo;
  private final int updateCheckIntervalMinutes;
  private final int updateRestartExitCode;
  private final String serverMode;
  private final int quicListenPort;
  private final String quicCertPath;
  private final String quicKeyPath;
  private final String quicAlpn;
  private final int quicMaxStreams;
  private final int quicMaxHandshakes;
  private final int quicIdleTimeoutMs;
  private final int quicHandshakeTimeoutMs;
  private final int quicTcpConnectTimeoutMs;
  private final int quicIngressRingSlots;
  private final boolean camouflageTcpEnabled;
  private final String camouflageTcpProxyHost;
  private final int camouflageTcpProxyPort;
  private final String camouflageHttpServerName;

  private final boolean quicTraceLog;
  private final boolean tokenAutoGenerated;

  private final boolean peerRelayEnabled;
  private final boolean quicRetryTokens;
  private final int relayMaxPerRemote;
  private final int relayMaxTotal;
  private final int relayMaxBudgetKbps;

  private final String relayIndexFile;
  private final String relayIndexPath;
  private final String opsHintsPath;
  private final String gossipIndexFile;
  private final String gossipIndexPath;
  private final String dhtFindPath;
  private final String dhtRpcListenUdp;
  private final String dhtRpcSecret;
  private final String clusterNodeId;
  private final int clusterListen;
  private final List<String> clusterPeers;
  private final int clusterGossipIntervalMs;
  private final String clusterMapPath;
  private final String clusterSessionsPath;
  private final String clusterClientsPath;
  private final boolean clusterHttpAuth;
  private final String clusterHttpSecret;

  private Config(List<Integer> listenPorts, String token, int udpChannels, String publicHost, boolean debug,
                 boolean updateEnabled, String updateRepo, int updateCheckIntervalMinutes, int updateRestartExitCode,
                 String serverMode, int quicListenPort, String quicCertPath, String quicKeyPath,
                 String quicAlpn, int quicMaxStreams, int quicMaxHandshakes, int quicIdleTimeoutMs,
                 int quicHandshakeTimeoutMs, int quicTcpConnectTimeoutMs, int quicIngressRingSlots,
                 boolean quicTraceLog, boolean tokenAutoGenerated,
                 boolean camouflageTcpEnabled, String camouflageTcpProxyHost, int camouflageTcpProxyPort, String camouflageHttpServerName,
                 boolean peerRelayEnabled, boolean quicRetryTokens, int relayMaxPerRemote, int relayMaxTotal, int relayMaxBudgetKbps,
                 String relayIndexFile, String relayIndexPath, String opsHintsPath,
                 String gossipIndexFile, String gossipIndexPath, String dhtFindPath, String dhtRpcListenUdp, String dhtRpcSecret,
                 String clusterNodeId, int clusterListen, List<String> clusterPeers, int clusterGossipIntervalMs, String clusterMapPath,
                 String clusterSessionsPath, String clusterClientsPath, boolean clusterHttpAuth, String clusterHttpSecret) {
    this.listenPorts = listenPorts;
    this.token = token;
    this.udpChannels = udpChannels;
    this.publicHost = publicHost != null ? publicHost : "";
    this.debug = debug;
    this.updateEnabled = updateEnabled;
    this.updateRepo = updateRepo != null ? updateRepo.trim() : "";
    this.updateCheckIntervalMinutes = updateCheckIntervalMinutes;
    this.updateRestartExitCode = updateRestartExitCode;
    this.serverMode = serverMode;
    this.quicListenPort = quicListenPort;
    this.quicCertPath = quicCertPath != null ? quicCertPath.trim() : "";
    this.quicKeyPath = quicKeyPath != null ? quicKeyPath.trim() : "";
    this.quicAlpn = quicAlpn != null ? quicAlpn.trim() : "volter";
    this.quicMaxStreams = quicMaxStreams;
    this.quicMaxHandshakes = quicMaxHandshakes;
    this.quicIdleTimeoutMs = quicIdleTimeoutMs;
    this.quicHandshakeTimeoutMs = quicHandshakeTimeoutMs;
    this.quicTcpConnectTimeoutMs = quicTcpConnectTimeoutMs;
    this.quicIngressRingSlots = quicIngressRingSlots;
    this.quicTraceLog = quicTraceLog;
    this.tokenAutoGenerated = tokenAutoGenerated;
    this.camouflageTcpEnabled = camouflageTcpEnabled;
    this.camouflageTcpProxyHost = camouflageTcpProxyHost != null ? camouflageTcpProxyHost.trim() : "";
    this.camouflageTcpProxyPort = camouflageTcpProxyPort;
    this.camouflageHttpServerName = camouflageHttpServerName != null ? camouflageHttpServerName.trim() : "nginx";
    this.peerRelayEnabled = peerRelayEnabled;
    this.quicRetryTokens = quicRetryTokens;
    this.relayMaxPerRemote = Math.max(1, relayMaxPerRemote);
    this.relayMaxTotal = Math.max(1, relayMaxTotal);
    this.relayMaxBudgetKbps = Math.max(0, relayMaxBudgetKbps);
    this.relayIndexFile = relayIndexFile != null ? relayIndexFile.trim() : "";
    this.relayIndexPath = relayIndexPath != null && !relayIndexPath.isBlank() ? relayIndexPath.trim() : "/volter/relay-index.json";
    this.opsHintsPath = opsHintsPath != null ? opsHintsPath.trim() : "";
    this.gossipIndexFile = gossipIndexFile != null ? gossipIndexFile.trim() : "";
    this.gossipIndexPath = gossipIndexPath != null && !gossipIndexPath.isBlank() ? gossipIndexPath.trim() : "/volter/gossip-nodes.json";
    this.dhtFindPath = dhtFindPath != null && !dhtFindPath.isBlank() ? dhtFindPath.trim() : "/volter/dht/find";
    this.dhtRpcListenUdp = dhtRpcListenUdp != null ? dhtRpcListenUdp.trim() : "";
    this.dhtRpcSecret = dhtRpcSecret != null ? dhtRpcSecret.trim() : "";
    this.clusterNodeId = clusterNodeId != null && !clusterNodeId.isBlank() ? clusterNodeId.trim() : "node-0";
    this.clusterListen = clusterListen;
    this.clusterPeers = clusterPeers != null ? clusterPeers : List.of();
    this.clusterGossipIntervalMs = Math.max(1_000, clusterGossipIntervalMs);
    this.clusterMapPath = clusterMapPath != null && !clusterMapPath.isBlank() ? clusterMapPath.trim() : "/volter/cluster-map.json";
    this.clusterSessionsPath = clusterSessionsPath != null && !clusterSessionsPath.isBlank() ? clusterSessionsPath.trim() : "/volter/cluster-sessions.json";
    this.clusterClientsPath = clusterClientsPath != null && !clusterClientsPath.isBlank() ? clusterClientsPath.trim() : "/volter/cluster-clients.json";
    this.clusterHttpAuth = clusterHttpAuth;
    this.clusterHttpSecret = clusterHttpSecret != null ? clusterHttpSecret.trim() : "";
  }

  String serverMode() { return serverMode; }
  int quicListenPort() { return quicListenPort; }
  String quicCertPath() { return quicCertPath; }
  String quicKeyPath() { return quicKeyPath; }
  String quicAlpn() { return quicAlpn; }
  int quicMaxStreams() { return quicMaxStreams; }
  int quicMaxHandshakes() { return quicMaxHandshakes; }
  int quicIdleTimeoutMs() { return quicIdleTimeoutMs; }
  int quicHandshakeTimeoutMs() { return quicHandshakeTimeoutMs; }
  int quicTcpConnectTimeoutMs() { return quicTcpConnectTimeoutMs; }
  int quicIngressRingSlots() { return quicIngressRingSlots; }
  boolean quicTraceLog() { return quicTraceLog; }
  boolean tokenAutoGenerated() { return tokenAutoGenerated; }
  boolean camouflageTcpEnabled() { return camouflageTcpEnabled; }
  String camouflageTcpProxyHost() { return camouflageTcpProxyHost; }
  int camouflageTcpProxyPort() { return camouflageTcpProxyPort; }
  String camouflageHttpServerName() { return camouflageHttpServerName; }
  boolean peerRelayEnabled() {
    return peerRelayEnabled;
  }
  boolean quicRetryTokens() {
    return quicRetryTokens;
  }

  int relayMaxPerRemote() {
    return relayMaxPerRemote;
  }

  int relayMaxTotal() {
    return relayMaxTotal;
  }

  int relayMaxBudgetKbps() {
    return relayMaxBudgetKbps;
  }

  String relayIndexFile() {
    return relayIndexFile;
  }

  String relayIndexPath() {
    return relayIndexPath;
  }

  String opsHintsPath() {
    return opsHintsPath;
  }

  String gossipIndexFile() {
    return gossipIndexFile;
  }

  String gossipIndexPath() {
    return gossipIndexPath;
  }

  String dhtFindPath() {
    return dhtFindPath;
  }

  String dhtRpcListenUdp() {
    return dhtRpcListenUdp;
  }

  String dhtRpcSecret() {
    if (dhtRpcSecret != null && !dhtRpcSecret.isBlank()) {
      return dhtRpcSecret;
    }
    return token != null ? token : "";
  }

  String clusterNodeId() {
    return clusterNodeId;
  }

  int clusterListen() {
    return clusterListen;
  }

  List<String> clusterPeers() {
    return clusterPeers;
  }

  int clusterGossipIntervalMs() {
    return clusterGossipIntervalMs;
  }

  String clusterMapPath() {
    return clusterMapPath;
  }

  String clusterSessionsPath() {
    return clusterSessionsPath;
  }

  String clusterClientsPath() {
    return clusterClientsPath;
  }

  boolean clusterHttpAuth() {
    return clusterHttpAuth;
  }

  String clusterHttpSecret() {
    return clusterHttpSecret;
  }

  String clusterHttpExpectedKey() {
    if (clusterHttpSecret != null && !clusterHttpSecret.isBlank()) {
      return clusterHttpSecret.trim();
    }
    return token != null ? token : "";
  }

  boolean tcpEnabled() { return !"quic-only".equals(serverMode); }
  boolean quicEnabled() { return !"tcp-only".equals(serverMode); }

  boolean updateEnabled() { return updateEnabled; }
  String updateRepo() { return updateRepo; }
  int updateCheckIntervalMinutes() { return updateCheckIntervalMinutes; }
  int updateRestartExitCode() { return updateRestartExitCode; }

  boolean debug() {
    return debug;
  }

  List<Integer> listenPorts() {
    return listenPorts;
  }

  String token() {
    return token;
  }

  int udpChannels() {
    return udpChannels;
  }

  String publicHost() {
    return publicHost;
  }

  static Config load(Path configPath) throws IOException {
    Properties p = new Properties();
    try (InputStream in = Files.newInputStream(configPath)) {
      p.load(in);
    }

    String portsStr = firstNonEmpty(p.getProperty("listenPorts"), p.getProperty("listenPort"));
    if (portsStr == null) throw new IOException("listenPorts is required");
    List<Integer> ports = parsePortsCsv(portsStr);
    if (ports.isEmpty()) throw new IOException("listenPorts is empty");

    String token = firstNonEmpty(p.getProperty("token"), null);
    boolean tokenAutoGenerated = false;
    if (token == null) {
      String connKey = firstNonEmpty(p.getProperty("connectionKey"), p.getProperty("volterKey"));
      token = tokenFromConnectionKey(connKey);
    }
    if (token == null) {
      token = randomToken(24);
      tokenAutoGenerated = true;
    }
    if (token.length() > 4096) throw new IOException("token too long");

    int udpChannels = parseInt(p.getProperty("udpChannels"), 4);
    if (udpChannels != 4) throw new IOException("udpChannels must be 4");

    String publicHost = firstNonEmpty(p.getProperty("publicHost"), "");
    boolean debug = "true".equalsIgnoreCase(p.getProperty("debug", "").trim());
    boolean updateEnabled = "true".equalsIgnoreCase(p.getProperty("update.enabled", "false").trim());
    String updateRepo = firstNonEmpty(p.getProperty("update.repo"), "ORG-FE/volter");
    int updateCheckIntervalMinutes = Math.max(15, parseInt(p.getProperty("update.checkIntervalMinutes"), 60));
    int updateRestartExitCode = parseInt(p.getProperty("update.restartExitCode"), 1);
    String serverMode = firstNonEmpty(p.getProperty("serverMode"), "tcp-only").toLowerCase();
    if (!serverMode.equals("tcp-only") && !serverMode.equals("quic-only") && !serverMode.equals("both")) {
      throw new IOException("bad serverMode: " + serverMode);
    }
    int quicListenPort = parseInt(p.getProperty("quicListenPort"), 0);
    String quicCertPath = firstNonEmpty(p.getProperty("quicCertPath"), "");
    String quicKeyPath = firstNonEmpty(p.getProperty("quicKeyPath"), "");
    String quicAlpn = firstNonEmpty(p.getProperty("quicAlpn"), "volter");

    int quicMaxStreams = Math.max(0, parseInt(p.getProperty("quicMaxStreams"), 128));
    int quicMaxHandshakes = Math.max(0, parseInt(p.getProperty("quicMaxHandshakes"), 512));
    int quicIdleTimeoutMs = Math.max(0, parseInt(p.getProperty("quicIdleTimeoutMs"), 900_000));
    int quicHandshakeTimeoutMs = Math.max(0, parseInt(p.getProperty("quicHandshakeTimeoutMs"), 60_000));
    int quicTcpConnectTimeoutMs = Math.max(1_000, parseInt(p.getProperty("quicTcpConnectTimeoutMs"), 10_000));
    int quicIngressRingSlots = Math.max(64, parseInt(p.getProperty("quicIngressRingSlots"), 4096));
    boolean quicTraceLog = "true".equalsIgnoreCase(p.getProperty("quicTraceLog", "").trim());
    boolean camouflageTcpEnabled = "true".equalsIgnoreCase(p.getProperty("camouflageTcpEnabled", "true").trim());
    String camouflageTcpProxyHost = firstNonEmpty(p.getProperty("camouflageTcpProxyHost"), "127.0.0.1");
    int camouflageTcpProxyPort = Math.max(0, parseInt(p.getProperty("camouflageTcpProxyPort"), 443));
    String camouflageHttpServerName = firstNonEmpty(p.getProperty("camouflageHttpServerName"), "nginx");
    boolean peerRelayEnabled = !"false".equalsIgnoreCase(p.getProperty("peerRelayEnabled", "true").trim());
    boolean quicRetryTokens = "true".equalsIgnoreCase(p.getProperty("quicRetryTokens", "false").trim());
    int relayMaxPerRemote = Math.max(1, parseInt(p.getProperty("relay.maxPerRemote"), 64));
    int relayMaxTotal = Math.max(1, parseInt(p.getProperty("relay.maxTotal"), 2048));
    int relayMaxBudgetKbps = Math.max(0, parseInt(p.getProperty("relay.maxBudgetKbps"), 10240));
    String relayIndexFile = p.getProperty("relayIndexFile", "").trim();
    String relayIndexPath = p.getProperty("relayIndexPath", "/volter/relay-index.json").trim();
    if (relayIndexPath.isEmpty()) {
      relayIndexPath = "/volter/relay-index.json";
    }
    String opsHintsPath = p.getProperty("opsHintsPath", "").trim();
    String gossipIndexFile = p.getProperty("gossipIndexFile", "").trim();
    String gossipIndexPath = p.getProperty("gossipIndexPath", "/volter/gossip-nodes.json").trim();
    if (gossipIndexPath.isEmpty()) {
      gossipIndexPath = "/volter/gossip-nodes.json";
    }
    String dhtFindPath = p.getProperty("dhtFindPath", "/volter/dht/find").trim();
    if (dhtFindPath.isEmpty()) {
      dhtFindPath = "/volter/dht/find";
    }
    String dhtRpcListenUdp = p.getProperty("dhtRpcListenUdp", "").trim();
    String dhtRpcSecret = p.getProperty("dhtRpcSecret", "").trim();
    String clusterNodeId = p.getProperty("cluster.nodeId", "node-0").trim();
    int clusterListen = parseInt(p.getProperty("cluster.listen"), 0);
    List<String> clusterPeers = parseCsvStrings(p.getProperty("cluster.peers"));
    int clusterGossipIntervalMs = Math.max(1_000, parseInt(p.getProperty("cluster.gossipIntervalMs"), 5_000));
    String clusterMapPath = p.getProperty("cluster.mapPath", "/volter/cluster-map.json").trim();
    if (clusterMapPath.isEmpty()) {
      clusterMapPath = "/volter/cluster-map.json";
    }
    String clusterSessionsPath = p.getProperty("cluster.sessionsPath", "/volter/cluster-sessions.json").trim();
    if (clusterSessionsPath.isEmpty()) {
      clusterSessionsPath = "/volter/cluster-sessions.json";
    }
    String clusterClientsPath = p.getProperty("cluster.clientsPath", "/volter/cluster-clients.json").trim();
    if (clusterClientsPath.isEmpty()) {
      clusterClientsPath = "/volter/cluster-clients.json";
    }
    boolean clusterHttpAuth = "true".equalsIgnoreCase(p.getProperty("cluster.httpAuth", "false").trim());
    String clusterHttpSecret = p.getProperty("cluster.httpSecret", "").trim();
    if (serverMode.equals("quic-only") || serverMode.equals("both")) {
      if (quicListenPort < 1 || quicListenPort > 65535) throw new IOException("bad quicListenPort");
      if (quicCertPath == null || quicCertPath.isBlank()) throw new IOException("quicCertPath is required");
      if (quicKeyPath == null || quicKeyPath.isBlank()) throw new IOException("quicKeyPath is required");
    }
    return new Config(ports, token, udpChannels, publicHost != null ? publicHost : "", debug,
        updateEnabled, updateRepo, updateCheckIntervalMinutes, updateRestartExitCode,
        serverMode, quicListenPort, quicCertPath, quicKeyPath, quicAlpn, quicMaxStreams, quicMaxHandshakes, quicIdleTimeoutMs,
        quicHandshakeTimeoutMs, quicTcpConnectTimeoutMs, quicIngressRingSlots,
        quicTraceLog, tokenAutoGenerated,
        camouflageTcpEnabled, camouflageTcpProxyHost, camouflageTcpProxyPort, camouflageHttpServerName,
        peerRelayEnabled, quicRetryTokens, relayMaxPerRemote, relayMaxTotal, relayMaxBudgetKbps,
        relayIndexFile,
        relayIndexPath,
        opsHintsPath,
        gossipIndexFile,
        gossipIndexPath,
        dhtFindPath,
        dhtRpcListenUdp,
        dhtRpcSecret,
        clusterNodeId,
        clusterListen,
        clusterPeers,
        clusterGossipIntervalMs,
        clusterMapPath,
        clusterSessionsPath,
        clusterClientsPath,
        clusterHttpAuth,
        clusterHttpSecret);
  }

  private static String firstNonEmpty(String a, String b) {
    if (a != null && !a.isBlank()) return a.trim();
    if (b != null && !b.isBlank()) return b.trim();
    return null;
  }

  private static int parseInt(String s, int def) throws IOException {
    if (s == null || s.isBlank()) return def;
    try {
      return Integer.parseInt(s.trim());
    } catch (NumberFormatException e) {
      throw new IOException("bad int: " + s, e);
    }
  }

  private static List<Integer> parsePortsCsv(String s) throws IOException {
    String[] parts = s.split(",");
    List<Integer> out = new ArrayList<>();
    for (String raw : parts) {
      String v = raw.trim();
      if (v.isEmpty()) continue;
      int port;
      try {
        port = Integer.parseInt(v);
      } catch (NumberFormatException e) {
        throw new IOException("bad port: " + v, e);
      }
      if (port < 1 || port > 65535) throw new IOException("bad port: " + port);
      if (!out.contains(port)) out.add(port);
    }
    return out;
  }

  private static List<String> parseCsvStrings(String s) {
    if (s == null || s.isBlank()) return List.of();
    String[] parts = s.split(",");
    List<String> out = new ArrayList<>();
    for (String raw : parts) {
      String v = raw.trim();
      if (!v.isEmpty()) out.add(v);
    }
    return out;
  }

  private static String tokenFromConnectionKey(String raw) {
    if (raw == null) return null;
    String s = raw.trim();
    if (s.isEmpty()) return null;
    if (!s.regionMatches(true, 0, "volter://", 0, "volter://".length())) return null;
    String body = s.substring("volter://".length()).trim();
    if (body.isEmpty()) return null;
    int cut = -1;
    for (int i = 0; i < body.length(); i++) {
      char c = body.charAt(i);
      if (c == '?' || c == '#') {
        cut = i;
        break;
      }
    }
    if (cut >= 0) body = body.substring(0, cut);
    if (body.isBlank()) return null;
    byte[] data = decodeAnyBase64(body);
    if (data == null || data.length == 0) return null;
    String json = new String(data, StandardCharsets.UTF_8);
    String key = jsonStringField(json, "k");
    if (key == null || key.isBlank()) key = jsonStringField(json, "token");
    if (key == null) return null;
    key = key.trim();
    return key.isEmpty() ? null : key;
  }

  private static byte[] decodeAnyBase64(String body) {
    try {
      return Base64.getUrlDecoder().decode(body);
    } catch (IllegalArgumentException ignored) {}
    int mod = body.length() % 4;
    if (mod != 0) {
      body = body + "====".substring(mod);
      try {
        return Base64.getUrlDecoder().decode(body);
      } catch (IllegalArgumentException ignored) {}
    }
    try {
      return Base64.getDecoder().decode(body);
    } catch (IllegalArgumentException ignored) {}
    return null;
  }

  private static String jsonStringField(String json, String field) {
    if (json == null || field == null || field.isBlank()) return null;
    String needle = "\"" + field + "\"";
    int i = json.indexOf(needle);
    if (i < 0) return null;
    int colon = json.indexOf(':', i + needle.length());
    if (colon < 0) return null;
    int start = -1;
    for (int p = colon + 1; p < json.length(); p++) {
      char ch = json.charAt(p);
      if (ch == '"') {
        start = p + 1;
        break;
      }
      if (!Character.isWhitespace(ch)) return null;
    }
    if (start < 0) return null;
    StringBuilder out = new StringBuilder();
    boolean esc = false;
    for (int p = start; p < json.length(); p++) {
      char ch = json.charAt(p);
      if (esc) {
        out.append(ch);
        esc = false;
        continue;
      }
      if (ch == '\\') {
        esc = true;
        continue;
      }
      if (ch == '"') return out.toString();
      out.append(ch);
    }
    return null;
  }

  private static String randomToken(int bytesLen) {
    byte[] b = new byte[Math.max(16, bytesLen)];
    new SecureRandom().nextBytes(b);
    return Base64.getUrlEncoder().withoutPadding().encodeToString(b);
  }
}

