package dev.c0redev.volter;

import java.io.IOException;
import java.net.InetSocketAddress;
import java.net.URI;
import java.nio.channels.ClosedChannelException;
import java.nio.channels.ServerSocketChannel;
import java.nio.channels.SocketChannel;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Base64;
import java.util.Collections;
import java.util.List;
import java.net.StandardSocketOptions;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.concurrent.ArrayBlockingQueue;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadPoolExecutor;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.logging.Logger;

public final class Main {
  private static Logger log;

  private static final Object RUN_LOCK = new Object();
  private static final AtomicInteger ACCEPT_THREAD_SEQ = new AtomicInteger();
  private static final AtomicInteger HANDSHAKE_THREAD_SEQ = new AtomicInteger();
  private static final AtomicInteger SESSION_THREAD_SEQ = new AtomicInteger();

  public static void main(String[] args) throws Exception {
    Path base = jarDir();
    Path cfgPath = base.resolve("config.properties");
    Config cfg = Config.load(cfgPath);
    Log.setDebug(cfg.debug());
    Log.setQuicTrace(cfg.quicTraceLog());

    DexoteServerKey dexoteKey = DexoteServerKey.loadOrCreate(base.resolve("dexote.key"));
    Dexote.ReplayCache replayCache = new MemReplayCache();

    DexoteUpstream.setNodeDexotePub(dexoteKey.pub());
    ClusterRuntime.get().setSelfDexotePub(dexoteKey.pubBase64());
    log = Log.logger(Main.class);
    if (cfg.quicTraceLog()) {
      log.info("quicTraceLog=true — UDP до codec, parent QUIC, Netty QUIC FINEST, токены");
    }
    log.info("Base: " + base);
    log.info("Ports: " + cfg.listenPorts());
    log.info("Mode: " + cfg.serverMode());
    log.info("IPv6: " + (Ipv6Detect.hasIPv6() ? "available" : "not available"));
    ClusterRuntime.get().start(cfg);
    if (cfg.tokenAutoGenerated()) {
      log.info("Token source: auto generated");
    }
    if (cfg.updateEnabled()) {
      Path jp = jarPath();
      if (jp != null) {
        Thread t = new Thread(new UpdateRunner(jp, cfg), "update-runner");
        t.setDaemon(true);
        t.start();
      }
    }
    String host = resolvePublicHost(cfg);
    log.info("Dexote server pubkey: " + dexoteKey.pubBase64());
    if (host != null && !host.isBlank()) {
      for (int port : cfg.listenPorts()) {
        log.info("Connection key: " + buildConnectionKey(hostPort(host, port), cfg.token(), dexoteKey.pubBase64()));
      }
    }

    int reactorThreads = Math.max(1, Runtime.getRuntime().availableProcessors());
    int sessionMax = Math.max(64, reactorThreads * 32);
    int acceptThreads = Math.max(1, cfg.listenPorts().size());
    int handshakeThreads = Math.max(16, reactorThreads * 2);
    int handshakeQueue = Math.max(256, sessionMax * 2);
    log.info("TCP reactor pool: " + reactorThreads + " threads");
    log.info("Accept pool: threads=" + acceptThreads);
    log.info("Handshake pool: threads=" + handshakeThreads + " queue=" + handshakeQueue);
    log.info("Session pool: core=" + Math.max(16, reactorThreads * 4) + " max=" + sessionMax);
    ExecutorService acceptPool = Executors.newFixedThreadPool(acceptThreads, r -> {
      Thread t = new Thread(r, "volter-accept-" + ACCEPT_THREAD_SEQ.incrementAndGet());
      t.setDaemon(true);
      return t;
    });
    ExecutorService handshakePool = new ThreadPoolExecutor(
        handshakeThreads,
        handshakeThreads,
        0L,
        TimeUnit.MILLISECONDS,
        new ArrayBlockingQueue<>(handshakeQueue),
        r -> {
          Thread t = new Thread(r, "volter-handshake-" + HANDSHAKE_THREAD_SEQ.incrementAndGet());
          t.setDaemon(true);
          return t;
        },
        new ThreadPoolExecutor.CallerRunsPolicy());
    ExecutorService streamPool = new ThreadPoolExecutor(
        Math.max(16, reactorThreads * 4),
        sessionMax,
        60L,
        TimeUnit.SECONDS,
        new ArrayBlockingQueue<>(sessionMax),
        r -> {
          Thread t = new Thread(r, "volter-session-" + SESSION_THREAD_SEQ.incrementAndGet());
          t.setDaemon(true);
          return t;
        },
        new ThreadPoolExecutor.CallerRunsPolicy());
    List<ServerSocketChannel> sockets = Collections.synchronizedList(new ArrayList<>());
    final QuicServer[] quicHolder = new QuicServer[1];
    final DhtRpcUdpServer[] dhtRpcHolder = new DhtRpcUdpServer[1];
    Runtime.getRuntime().addShutdownHook(new Thread(() -> {
      log.info("Shutdown: closing TCP listeners and QUIC (release ports for next start)");
      List<ServerSocketChannel> copy;
      synchronized (sockets) {
        copy = new ArrayList<>(sockets);
      }
      for (ServerSocketChannel ss : copy) {
        try {
          ss.close();
        } catch (IOException ignored) {}
      }
      if (quicHolder[0] != null) {
        try {
          quicHolder[0].close();
        } catch (Exception ignored) {}
      }
      if (dhtRpcHolder[0] != null) {
        try {
          dhtRpcHolder[0].close();
        } catch (Exception ignored) {}
      }
      ClusterRuntime.get().stop();
      streamPool.shutdown();
      handshakePool.shutdown();
      acceptPool.shutdown();
      awaitPool(acceptPool, "accept");
      awaitPool(handshakePool, "handshake");
      awaitPool(streamPool, "stream");
      synchronized (RUN_LOCK) {
        RUN_LOCK.notifyAll();
      }
    }, "volter-shutdown"));

    try (UdpSessions udp = new UdpSessions(cfg.udpChannels())) {
      if (cfg.quicEnabled()) {
        quicHolder[0] = new QuicServer(cfg, udp, streamPool, dexoteKey, replayCache);
        quicHolder[0].start();
      }
      dhtRpcHolder[0] = DhtRpcUdpServer.startIfEnabled(cfg);
      if (cfg.tcpEnabled()) {
        for (int port : cfg.listenPorts()) {
          ServerSocketChannel ss = ServerSocketChannel.open();
          ss.setOption(StandardSocketOptions.SO_REUSEADDR, true);
          ss.bind(new InetSocketAddress(port));
          sockets.add(ss);
          acceptPool.submit(() -> acceptLoop(ss, cfg, udp, handshakePool, streamPool, dexoteKey, replayCache));
        }
      }

      synchronized (RUN_LOCK) {
        RUN_LOCK.wait();
      }
    } finally {
      for (ServerSocketChannel ss : sockets) {
        try {
          ss.close();
        } catch (IOException ignored) {}
      }
      if (quicHolder[0] != null) {
        try {
          quicHolder[0].close();
        } catch (Exception ignored) {}
      }
      if (dhtRpcHolder[0] != null) {
        try {
          dhtRpcHolder[0].close();
        } catch (Exception ignored) {}
      }
      ClusterRuntime.get().stop();
      streamPool.shutdown();
      handshakePool.shutdown();
      acceptPool.shutdown();
      awaitPool(acceptPool, "accept");
      awaitPool(handshakePool, "handshake");
      awaitPool(streamPool, "stream");
    }
  }

  private static void awaitPool(ExecutorService pool, String name) {
    try {
      if (!pool.awaitTermination(8, TimeUnit.SECONDS)) {
        pool.shutdownNow();
        if (!pool.awaitTermination(4, TimeUnit.SECONDS)) {
          log.warning("pool " + name + " did not terminate cleanly");
        }
      }
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      pool.shutdownNow();
    }
  }

  private static void acceptLoop(
    ServerSocketChannel ss,
    Config cfg,
    UdpSessions udp,
    ExecutorService handshakePool,
    ExecutorService streamPool,
    DexoteServerKey dexoteKey,
    Dexote.ReplayCache replayCache
  ) {
    while (ss.isOpen()) {
      try {
        SocketChannel s = ss.accept();
        s.setOption(StandardSocketOptions.TCP_NODELAY, true);
        s.setOption(StandardSocketOptions.SO_KEEPALIVE, true);
        try {
          handshakePool.execute(new ConnectionHandler(s.socket(), cfg, udp, streamPool, dexoteKey, replayCache));
        } catch (java.util.concurrent.RejectedExecutionException e) {
          String remote = String.valueOf(s.getRemoteAddress());
          try {
            s.close();
          } catch (IOException ignored) {}
          if (!ss.isOpen()) break;
          log.warning("handshake pool rejected connection from " + remote);
        }
      } catch (ClosedChannelException e) {
        break;
      } catch (IOException e) {
        if (!ss.isOpen()) {
          break;
        }
        String msg = e.getMessage();
        log.warning("accept error: " + (msg != null && !msg.isBlank() ? msg : e.getClass().getSimpleName()));
      }
    }
  }

  private static Path jarDir() {
    try {
      String p = Main.class.getProtectionDomain().getCodeSource().getLocation().toURI().getPath();
      Path jar = Paths.get(p).toAbsolutePath().normalize();
      Path dir = jar.getParent();
      if (dir != null) return dir;
    } catch (Exception ignored) {
    }
    return Paths.get("").toAbsolutePath().normalize();
  }

  static Path jarPath() {
    try {
      String p = Main.class.getProtectionDomain().getCodeSource().getLocation().toURI().getPath();
      return Paths.get(p).toAbsolutePath().normalize();
    } catch (Exception e) {
      return null;
    }
  }

  private static String buildConnectionKey(String server, String token, String dexotePub) {
    String payload = "{\"s\":\"" + jsonEsc(server) + "\",\"k\":\"" + jsonEsc(token)
        + "\",\"p\":\"" + jsonEsc(dexotePub) + "\"}";
    String b64 = Base64.getUrlEncoder().withoutPadding().encodeToString(payload.getBytes(StandardCharsets.UTF_8));
    return "volter://" + b64;
  }

  private static String jsonEsc(String s) {
    if (s == null || s.isEmpty()) return "";
    StringBuilder out = new StringBuilder(s.length() + 8);
    for (int i = 0; i < s.length(); i++) {
      char c = s.charAt(i);
      if (c == '\\' || c == '"') out.append('\\');
      out.append(c);
    }
    return out.toString();
  }

  private static String resolvePublicHost(Config cfg) {
    String fromCfg = cfg.publicHost();
    if (fromCfg != null && !fromCfg.isBlank()) {
      return fromCfg.trim();
    }
    String[] endpoints = new String[] {
        "https://api.ipify.org",
        "https://checkip.amazonaws.com",
        "https://ipv4.icanhazip.com",
    };
    HttpClient client = HttpClient.newBuilder().connectTimeout(java.time.Duration.ofSeconds(4)).build();
    for (String u : endpoints) {
      try {
        HttpRequest req = HttpRequest.newBuilder(URI.create(u))
            .timeout(java.time.Duration.ofSeconds(4))
            .GET()
            .build();
        HttpResponse<String> resp = client.send(req, HttpResponse.BodyHandlers.ofString());
        if (resp.statusCode() < 200 || resp.statusCode() >= 300) continue;
        String ip = resp.body() == null ? "" : resp.body().trim();
        if (ip.isBlank()) continue;
        if (ip.contains(":")) return "[" + ip + "]";
        return ip;
      } catch (Exception ignored) {}
    }
    return "";
  }

  private static String hostPort(String host, int port) {
    String h = host == null ? "" : host.trim();
    if (h.isEmpty()) return "";
    if (h.contains(":") && !h.startsWith("[") && !h.endsWith("]")) {
      h = "[" + h + "]";
    }
    return h + ":" + port;
  }
}
